[tool.poetry]
name = "sk-python-flask-chatgpt-plugin"
version = "0.1.0"
description = "A starter application using the semantic kernel in a Flask backend that can be imported as a ChatGPT plugin"
authors = ["Microsoft <SK-Support@microsoft.com>"]
readme = "README.md"
packages = [{include = "sk_python_flask_chatgpt_plugin"}]

[tool.poetry.dependencies]
python = "^3.10"
semantic-kernel = "^1.41.0"
flask = "^3.1.3"
flask-cors = "^6.0.2"

[tool.poetry.group.dev.dependencies]
black = "^26.3.1"
ruff = "^0.15.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
